### ISSUE TITLE
Quick thanks

### ISSUE THREAD

**Issue by osteel** [JamesHemery/laravel-uuid#2]
This is not an issue, just a quick thank you as this package is exactly what I was looking for. I have been using my own trait for quite some time and thought I should make a package out of it instead of copying it over from project to project again and again.

Thought I'd make a quick search for something similar before putting my own out there and ended up finding yours, which does exactly the same thing, even a bit better.

I don't understand why similar projects using inheritance instead of a trait seem to have more success - this is clearly _not_ an inheritance situation, a trait is definitely the way to go in my opinion.

Just thought you'd like to know your work hasn't gone unnoticed!

Cheers

**Comment by JamesHemery** [comment]
Thank you very much for your feedback, it's nice of you to take the time to do this. It's the same for me, during my research I had essentially found packages that used the inheritance, I find that a trait meets this need more, so I had to make one that corresponds more to my needs. 

Have a nice day!
