### ISSUE TITLE
PHP 8 Support Issue

### ISSUE THREAD

**Issue by Foysal50x** [JamesHemery/laravel-uuid#5]
Please add support for PHP 8. 

I'm unable to install this package. 

PHP version: PHP 8.0.0 (cli)
OS : macOS Big sure 11.0.1 

Error: 

 [InvalidArgumentException]                                                                                                 
  Package jamesh/laravel-uuid has a PHP requirement incompatible with your PHP version, PHP extensions and Composer version

**Comment by JamesHemery** [comment]
Hi,

Solved by #6 in version 1.0.6.
